Repository terraform-providers/terraform-provider-telefonicaopencloud, pull requests merged in 2018-09, with the labels that each got.

#8 Add Firewall resource support
  telefonicaopencloud/config.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_fw_firewall_group_v2.go
  telefonicaopencloud/resource_telefonicaopencloud_fw_firewall_group_v2_test.go
  telefonicaopencloud/resource_telefonicaopencloud_fw_policy_v2.go
  telefonicaopencloud/resource_telefonicaopencloud_fw_policy_v2_test.go
  telefonicaopencloud/resource_telefonicaopencloud_fw_rule_v2.go
  telefonicaopencloud/resource_telefonicaopencloud_fw_rule_v2_test.go
  telefonicaopencloud/types.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/firewall_groups/errors.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/firewall_groups/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/firewall_groups/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/firewall_groups/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/policies/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/policies/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/policies/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/routerinsertion/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/routerinsertion/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/routerinsertion/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/rules/errors.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/rules/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/rules/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/extensions/fwaas_v2/rules/urls.go
  vendor/vendor.json
  website/docs/r/fw_firewall_group_v2.html.markdown
  website/docs/r/fw_policy_v2.html.markdown
  website/docs/r/fw_rule_v2.html.markdown
  website/telefonicaopencloud.erb
Labels: size/XXL

#9 fix as config parameter of flavor
  telefonicaopencloud/provider_test.go
  telefonicaopencloud/resource_telefonicaopencloud_as_configuration_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_as_configuration_v1_test.go
  telefonicaopencloud/resource_telefonicaopencloud_as_group_v1_test.go
  telefonicaopencloud/resource_telefonicaopencloud_as_policy_v1_test.go
Labels: size/S

#10 Add RDS resource support
  telefonicaopencloud/config.go
  telefonicaopencloud/data_source_telefonicaopencloud_rds_flavors_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_rds_flavors_v1_test.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_rds_instance_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_rds_instance_v1_test.go
  website/docs/d/rds_flavors_v1.html.markdown
  website/docs/r/rds_instance_v1.html.markdown
  website/telefonicaopencloud.erb
Labels: size/XXL

#6 Add RTS stack and software Configuration resources
  telefonicaopencloud/config.go
  telefonicaopencloud/data_source_telefonicaopencloud_rts_software_config_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_rts_software_config_v1_test.go
  telefonicaopencloud/data_source_telefonicaopencloud_rts_stack_resource_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_rts_stack_resource_v1_test.go
  telefonicaopencloud/data_source_telefonicaopencloud_rts_stack_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_rts_stack_v1_test.go
  telefonicaopencloud/import_telefonicaopencloud_rts_software_config_v1_test.go
  telefonicaopencloud/import_telefonicaopencloud_rts_stack_v1_test.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_rts_software_config_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_rts_software_config_v1_test.go
  telefonicaopencloud/resource_telefonicaopencloud_rts_stack_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_rts_stack_v1_test.go
  telefonicaopencloud/structure.go
  telefonicaopencloud/utils.go
  telefonicaopencloud/validators.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/softwareconfig/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/softwareconfig/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/softwareconfig/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/softwareconfig/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stackresources/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stackresources/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stackresources/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stackresources/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacks/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacks/environment.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacks/errors.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacks/fixtures.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacks/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacks/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacks/template.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacks/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacks/utils.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacktemplates/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacktemplates/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacktemplates/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/rts/v1/stacktemplates/urls.go
  vendor/vendor.json
  website/docs/d/rts_software_config.html.markdown
  website/docs/d/rts_stack_resource_v1.html.md
  website/docs/d/rts_stack_v1.html.md
  website/docs/r/rts_software_config_v1.html.markdown
  website/docs/r/rts_stack_v1.html.md
  website/telefonicaopencloud.erb
Labels: size/XXL

#5 Add VPC and Subnet resource
  telefonicaopencloud/config.go
  telefonicaopencloud/data_source_telefonicaopencloud_vpc_subnet_ids_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_vpc_subnet_ids_v1_test.go
  telefonicaopencloud/data_source_telefonicaopencloud_vpc_subnet_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_vpc_subnet_v1_test.go
  telefonicaopencloud/data_source_telefonicaopencloud_vpc_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_vpc_v1_test.go
  telefonicaopencloud/import_telefonicaopencloud_vpc_subnet_v1_test.go
  telefonicaopencloud/import_telefonicaopencloud_vpc_v1_test.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_vpc_subnet_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_vpc_subnet_v1_test.go
  telefonicaopencloud/resource_telefonicaopencloud_vpc_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_vpc_v1_test.go
  telefonicaopencloud/validators.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/subnets/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/subnets/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/subnets/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/subnets/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/vpcs/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/vpcs/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/vpcs/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v1/vpcs/urls.go
  vendor/vendor.json
  website/docs/d/vpc_subnet_ids_v1.html.md
  website/docs/d/vpc_subnet_v1.html.md
  website/docs/d/vpc_v1.html.markdown
  website/docs/r/vpc_subnet_v1.html.md
  website/docs/r/vpc_v1.html.markdown
  website/telefonicaopencloud.erb
Labels: size/XXL

#17 Modify Volume delete interface
  telefonicaopencloud/config.go
  telefonicaopencloud/import_telefonicaopencloud_blockstorage_volume_v2_test.go
  telefonicaopencloud/resource_telefonicaopencloud_blockstorage_volume_v2.go
  telefonicaopencloud/resource_telefonicaopencloud_blockstorage_volume_v2_test.go
  vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/v2/volumes/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/v2/volumes/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/v2/volumes/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/v2/volumes/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/blockstorage/v2/volumes/util.go
  vendor/github.com/huaweicloud/golangsdk/openstack/compute/v2/extensions/volumeattach/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/compute/v2/extensions/volumeattach/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/compute/v2/extensions/volumeattach/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/compute/v2/extensions/volumeattach/urls.go
  vendor/vendor.json
  website/docs/r/blockstorage_volume_v2.html.markdown
Labels: size/XL
