Repository terraform-providers/terraform-provider-telefonicaopencloud, pull requests merged in 2018-12, with the labels that each got.

#16 Add CSBS Backup and Policy service
  examples/csbs-backup-with-ecs/main.tf
  examples/csbs-backup-with-ecs/variables.tf
  telefonicaopencloud/config.go
  telefonicaopencloud/data_source_telefonicaopencloud_csbs_backup_policy_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_csbs_backup_policy_v1_test.go
  telefonicaopencloud/data_source_telefonicaopencloud_csbs_backup_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_csbs_backup_v1_test.go
  telefonicaopencloud/import_telefonicaopencloud_csbs_backup_policy_v1_test.go
  telefonicaopencloud/import_telefonicaopencloud_csbs_backup_v1_test.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_csbs_backup_policy_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_csbs_backup_policy_v1_test.go
  telefonicaopencloud/resource_telefonicaopencloud_csbs_backup_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_csbs_backup_v1_test.go
  vendor/github.com/huaweicloud/golangsdk/auth_aksk_options.go
  vendor/github.com/huaweicloud/golangsdk/auth_option_provider.go
  vendor/github.com/huaweicloud/golangsdk/auth_options.go
  vendor/github.com/huaweicloud/golangsdk/errors.go
  vendor/github.com/huaweicloud/golangsdk/internal/pkg.go
  vendor/github.com/huaweicloud/golangsdk/internal/util.go
  vendor/github.com/huaweicloud/golangsdk/openstack/client.go
  vendor/github.com/huaweicloud/golangsdk/openstack/client_extension.go
  vendor/github.com/huaweicloud/golangsdk/openstack/csbs/v1/backup/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/csbs/v1/backup/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/csbs/v1/backup/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/csbs/v1/backup/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/csbs/v1/policies/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/csbs/v1/policies/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/csbs/v1/policies/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/csbs/v1/policies/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/endpoint_util.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/endpoints/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/endpoints/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/endpoints/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/endpoints/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/projects/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/projects/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/projects/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/projects/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/services/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/services/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/services/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/identity/v3/services/urls.go
  vendor/github.com/huaweicloud/golangsdk/provider_client.go
  vendor/github.com/huaweicloud/golangsdk/results.go
  vendor/github.com/huaweicloud/golangsdk/service_client.go
  vendor/github.com/huaweicloud/golangsdk/signer_helper.go
  vendor/vendor.json
  website/docs/d/csbs_backup_policy_v1.html.markdown
  website/docs/d/csbs_backup_v1.html.markdown
  website/docs/r/csbs_backup_policy_v1.html.markdown
  website/docs/r/csbs_backup_v1.html.markdown
  website/telefonicaopencloud.erb
Labels: size/XXL

#22 Switch ci go1.11
  .travis.yml
  README.md
  telefonicaopencloud/resource_telefonicaopencloud_as_group_v1.go
Labels: size/XS

#19 Add DCS Service
  telefonicaopencloud/config.go
  telefonicaopencloud/data_source_telefonicaopencloud_dcs_az_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_dcs_az_v1_test.go
  telefonicaopencloud/data_source_telefonicaopencloud_dcs_maintainwindow_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_dcs_maintainwindow_v1_test.go
  telefonicaopencloud/data_source_telefonicaopencloud_dcs_product_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_dcs_product_v1_test.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_dcs_instance_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_dcs_instance_v1_test.go
  vendor/github.com/huaweicloud/golangsdk/openstack/client.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/availablezones/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/availablezones/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/availablezones/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/instances/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/instances/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/instances/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/maintainwindows/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/maintainwindows/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/maintainwindows/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/products/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/products/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dcs/v1/products/urls.go
  vendor/vendor.json
  website/docs/d/dcs_az_v1.html.markdown
  website/docs/d/dcs_maintainwindow_v1.html.markdown
  website/docs/d/dcs_product_v1.html.markdown
  website/docs/r/dcs_instance_v1.html.markdown
  website/telefonicaopencloud.erb
Labels: dependencies, documentation, size/XXL

#21 Add CTS Tracker service
  examples/cts_tracker.tf
  telefonicaopencloud/config.go
  telefonicaopencloud/data_source_telefonicaopencloud_cts_tracker_v1.go
  telefonicaopencloud/data_source_telefonicaopencloud_cts_tracker_v1_test.go
  telefonicaopencloud/import_telefonicaopencloud_cts_tracker_v1_test.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_cts_tracker_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_cts_tracker_v1_test.go
  vendor/github.com/huaweicloud/golangsdk/openstack/cts/v1/tracker/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/cts/v1/tracker/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/cts/v1/tracker/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/cts/v1/tracker/urls.go
  vendor/vendor.json
  website/docs/d/cts_tracker_v1.html.markdown
  website/docs/r/cts_tracker_v1.html.markdown
  website/telefonicaopencloud.erb
Labels: dependencies, documentation, size/XL

#18 Add VBS Backup and Policy service
  examples/vbs-backup-with-volume/main.tf
  examples/vbs-backup-with-volume/variables.tf
  telefonicaopencloud/config.go
  telefonicaopencloud/data_source_telefonicaopencloud_vbs_backup_policy_v2.go
  telefonicaopencloud/data_source_telefonicaopencloud_vbs_backup_policy_v2_test.go
  telefonicaopencloud/data_source_telefonicaopencloud_vbs_backup_v2.go
  telefonicaopencloud/data_source_telefonicaopencloud_vbs_backup_v2_test.go
  telefonicaopencloud/import_telefonicaopencloud_vbs_backup_policy_v2_test.go
  telefonicaopencloud/import_telefonicaopencloud_vbs_backup_v2_test.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_vbs_backup_policy_v2.go
  telefonicaopencloud/resource_telefonicaopencloud_vbs_backup_policy_v2_test.go
  telefonicaopencloud/resource_telefonicaopencloud_vbs_backup_v2.go
  telefonicaopencloud/resource_telefonicaopencloud_vbs_backup_v2_test.go
  telefonicaopencloud/validators.go
  vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/backups/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/backups/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/backups/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/backups/results_job.go
  vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/backups/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/policies/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/policies/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/policies/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/vbs/v2/policies/urls.go
  vendor/vendor.json
  website/docs/d/vbs_backup_policy_v2.html.markdown
  website/docs/d/vbs_backup_v2.html.markdown
  website/docs/r/vbs_backup_policy_v2.html.markdown
  website/docs/r/vbs_backup_v2.html.markdown
  website/telefonicaopencloud.erb
Labels: dependencies, documentation, size/XXL

#15 Add DMS service feature
  telefonicaopencloud/config.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_dms_group_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_dms_group_v1_test.go
  telefonicaopencloud/resource_telefonicaopencloud_dms_queue_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_dms_queue_v1_test.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dms/v1/groups/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dms/v1/groups/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dms/v1/groups/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dms/v1/queues/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dms/v1/queues/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/dms/v1/queues/urls.go
  vendor/vendor.json
  website/docs/r/dms_group_v1.html.markdown
  website/docs/r/dms_queue_v1.html.markdown
  website/telefonicaopencloud.erb
Labels: dependencies, documentation, size/XXL

#23 Add BMS server resource
  telefonicaopencloud/compute_bms_v2_server_addresses.go
  telefonicaopencloud/config.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/provider_test.go
  telefonicaopencloud/resource_telefonicaopencloud_compute_bms_server_v2.go
  telefonicaopencloud/resource_telefonicaopencloud_compute_bms_server_v2_test.go
  vendor/github.com/huaweicloud/golangsdk/openstack/bms/v2/servers/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/bms/v2/servers/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/bms/v2/servers/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/bms/v2/servers/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/bms/v2/tags/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/bms/v2/tags/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/bms/v2/tags/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/bms/v2/tags/urls.go
  vendor/vendor.json
  website/docs/r/compute_bms_server_v2.html.markdown
  website/telefonicaopencloud.erb
Labels: dependencies, documentation, size/XXL

#24 Add mrs
  telefonicaopencloud/config.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_mrs_cluster_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_mrs_cluster_v1_test.go
  telefonicaopencloud/resource_telefonicaopencloud_mrs_job_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_mrs_job_v1_test.go
  vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/cluster/urls.go
  vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/job/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/job/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/mrs/v1/job/urls.go
  vendor/vendor.json
  website/docs/r/mrs_cluster_v1.html.markdown
  website/docs/r/mrs_job_v1.html.markdown
  website/telefonicaopencloud.erb
Labels: dependencies, documentation, size/XXL

#25 Add maas
  telefonicaopencloud/config.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/provider_test.go
  telefonicaopencloud/resource_telefonicaopencloud_maas_task_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_maas_task_v1_test.go
  vendor/github.com/huaweicloud/golangsdk/openstack/client.go
  vendor/github.com/huaweicloud/golangsdk/openstack/maas/v1/task/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/maas/v1/task/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/maas/v1/task/urls.go
  vendor/vendor.json
  website/docs/r/maas_task_v1.html.markdown
  website/telefonicaopencloud.erb
Labels: dependencies, documentation, size/XL

#26 Add antiddos
  telefonicaopencloud/config.go
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_antiddos_v1.go
  telefonicaopencloud/resource_telefonicaopencloud_antiddos_v1_test.go
  telefonicaopencloud/validators.go
  vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/API-cn.md
  vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/API-en.md
  vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/antiddos/v1/antiddos/url.go
  vendor/vendor.json
  website/docs/r/antiddos_v1.html.markdown
  website/telefonicaopencloud.erb
Labels: dependencies, documentation, size/XXL

#27 Add vpc peering
  telefonicaopencloud/provider.go
  telefonicaopencloud/resource_telefonicaopencloud_vpc_peering_connection_accepter_v2.go
  telefonicaopencloud/resource_telefonicaopencloud_vpc_peering_connection_accepter_v2_test.go
  telefonicaopencloud/resource_telefonicaopencloud_vpc_peering_connection_v2.go
  telefonicaopencloud/resource_telefonicaopencloud_vpc_peering_connection_v2_test.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/peerings/doc.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/peerings/requests.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/peerings/results.go
  vendor/github.com/huaweicloud/golangsdk/openstack/networking/v2/peerings/urls.go
  vendor/vendor.json
  website/docs/r/vpc_peering_accepter_v2.html.md
  website/docs/r/vpc_peering_v2.html.md
  website/telefonicaopencloud.erb
Labels: dependencies, documentation, size/XXL
